<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Details_w-full h-48 object-cover rounded-lg mb-4</name>
   <tag></tag>
   <elementGuidId>c30d681c-727d-49da-baff-0105f7720b10</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.bg-white.p-6.rounded-lg.shadow-lg.w-96 > img.w-full.h-48.object-cover.rounded-lg.mb-4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[3]/div/img</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@src = 'https://res.cloudinary.com/emerging-it/image/upload/v1724240584/mangaImage/lyj3i7qwtp3f2qz59so1.jpg' and @alt = 'Attack on Titan']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>0a942191-0198-4651-8f13-c75ee3e5c397</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://res.cloudinary.com/emerging-it/image/upload/v1724240584/mangaImage/lyj3i7qwtp3f2qz59so1.jpg</value>
      <webElementGuid>9283c600-f05f-44d2-aa49-7a1311561ab5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Attack on Titan</value>
      <webElementGuid>74fb2223-44ad-44dc-99cc-00329c090876</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full h-48 object-cover rounded-lg mb-4</value>
      <webElementGuid>2d2f71b1-4384-4bfc-8070-44c41c11029b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;flex flex-col items-center p-6 bg-gray-100 min-h-screen&quot;]/div[@class=&quot;fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center&quot;]/div[@class=&quot;bg-white p-6 rounded-lg shadow-lg w-96&quot;]/img[@class=&quot;w-full h-48 object-cover rounded-lg mb-4&quot;]</value>
      <webElementGuid>99f79d05-636e-4aa0-96f6-f3fbbf4d0df3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/div/img</value>
      <webElementGuid>4b6febd2-1033-4925-af13-0b0963185225</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Attack on Titan'])[2]</value>
      <webElementGuid>d0d238ec-da3f-43b7-843f-0efb6d4d2b9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/img</value>
      <webElementGuid>a36547e4-5b2c-4214-a23d-97b6dc738c9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://res.cloudinary.com/emerging-it/image/upload/v1724240584/mangaImage/lyj3i7qwtp3f2qz59so1.jpg' and @alt = 'Attack on Titan']</value>
      <webElementGuid>804c1186-004d-4fe3-b06e-636e3fed2ad0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
